# Generated by Django 2.0.3 on 2018-03-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qSite', '0002_auto_20180330_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='object_id',
            field=models.PositiveIntegerField(null=True, verbose_name='id of related object'),
        ),
    ]
