# Generated by Django 2.0.3 on 2018-03-30 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qSite', '0003_auto_20180330_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='value',
            field=models.IntegerField(choices=[('DISLIKE', -1), ('LIKE', 1)], verbose_name='Like or dislike'),
        ),
    ]
