# Generated by Django 2.0.3 on 2018-03-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qSite', '0007_auto_20180330_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='value',
            field=models.IntegerField(choices=[(-1, -1), (1, 1)], verbose_name='Like or dislike'),
        ),
    ]
