# Generated by Django 2.0.3 on 2018-03-30 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('qSite', '0009_auto_20180330_2032'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('author', 'content_type', 'object_id')},
        ),
    ]
