# Generated by Django 2.0.3 on 2018-04-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qSite', '0013_auto_20180413_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=False, default=None, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
