# Generated by Django 2.0.3 on 2018-04-13 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qSite', '0015_auto_20180413_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
