# Generated by Django 2.0.3 on 2018-05-06 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qSite', '0017_auto_20180413_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='nobody.jpg', upload_to='uploads/%Y/%m/%d/', verbose_name='Avatar image of the user'),
        ),
    ]
