# Generated by Django 2.0.3 on 2018-05-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qSite', '0018_auto_20180506_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='questions', to='qSite.Tag', verbose_name='Tags of the question'),
        ),
    ]
